## ========================================================================== ##
## -------------------------------------------------------------------------- ##
##                                  TEST 08                                   ##
## -------------------------------------------------------------------------- ##
## ========================================================================== ##

# -- Modifier: board_reduce -- #
B = create_board()
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
B = board_reduce(B, 'W')
board_score(B)
B = board_fill_position(B, C, 2)
B = board_reduce(B, 'W')
board_score(B)
# - (additional hidden tests) - #
B = create_board()
B = board_fill_position(B, create_coordinate(1, 4), 2)
B = board_fill_position(B, create_coordinate(2, 3), 2)
B = board_fill_position(B, create_coordinate(3, 2), 2)
B = board_fill_position(B, create_coordinate(4, 1), 2)
B = board_reduce(B, 'W')
print_board(B)
B = create_board()
B = board_fill_position(B, create_coordinate(1, 3), 2)
B = board_fill_position(B, create_coordinate(1, 4), 2)
B = board_fill_position(B, create_coordinate(2, 2), 2)
B = board_fill_position(B, create_coordinate(2, 3), 2)
B = board_fill_position(B, create_coordinate(3, 1), 2)
B = board_fill_position(B, create_coordinate(3, 2), 2)
B = board_fill_position(B, create_coordinate(4, 1), 2)
B = board_fill_position(B, create_coordinate(4, 4), 2)
B = board_reduce(B, 'E')
print_board(B)
B = create_board()
B = board_fill_position(B, create_coordinate(1, 2), 2)
B = board_fill_position(B, create_coordinate(1, 4), 2)
B = board_fill_position(B, create_coordinate(2, 1), 2)
B = board_fill_position(B, create_coordinate(2, 3), 2)
B = board_fill_position(B, create_coordinate(3, 1), 2)
B = board_fill_position(B, create_coordinate(3, 2), 2)
B = board_fill_position(B, create_coordinate(3, 3), 2)
B = board_fill_position(B, create_coordinate(4, 1), 2)
B = board_fill_position(B, create_coordinate(4, 3), 2)
B = board_fill_position(B, create_coordinate(4, 4), 2)
B = board_reduce(B, 'W')
print_board(B)
B = create_board()
B = board_fill_position(B, create_coordinate(1, 1), 2)
B = board_fill_position(B, create_coordinate(1, 3), 4)
B = board_fill_position(B, create_coordinate(1, 4), 4)
B = board_fill_position(B, create_coordinate(2, 1), 2)
B = board_fill_position(B, create_coordinate(2, 2), 2)
B = board_fill_position(B, create_coordinate(2, 3), 2)
B = board_fill_position(B, create_coordinate(2, 4), 2)
B = board_fill_position(B, create_coordinate(3, 2), 2)
B = board_fill_position(B, create_coordinate(3, 3), 2)
B = board_fill_position(B, create_coordinate(4, 1), 2)
B = board_fill_position(B, create_coordinate(4, 2), 2)
B = board_fill_position(B, create_coordinate(4, 4), 2)
B = board_reduce(B, 'N')
print_board(B)
B = create_board()
B = board_fill_position(B, create_coordinate(1, 1), 2)
B = board_fill_position(B, create_coordinate(1, 2), 2)
B = board_fill_position(B, create_coordinate(1, 4), 4)
B = board_fill_position(B, create_coordinate(2, 1), 2)
B = board_fill_position(B, create_coordinate(2, 2), 2)
B = board_fill_position(B, create_coordinate(2, 3), 4)
B = board_fill_position(B, create_coordinate(3, 2), 4)
B = board_fill_position(B, create_coordinate(3, 3), 2)
B = board_fill_position(B, create_coordinate(3, 4), 2)
B = board_fill_position(B, create_coordinate(4, 1), 4)
B = board_fill_position(B, create_coordinate(4, 3), 2)
B = board_fill_position(B, create_coordinate(4, 4), 2)
B = board_reduce(B, 'S')
print_board(B)
B = create_board()
B = board_fill_position(B, create_coordinate(1, 1), 2)
B = board_fill_position(B, create_coordinate(1, 3), 2)
B = board_fill_position(B, create_coordinate(1, 4), 4)
B = board_fill_position(B, create_coordinate(2, 2), 2)
B = board_fill_position(B, create_coordinate(2, 3), 2)
B = board_fill_position(B, create_coordinate(2, 4), 4)
B = board_fill_position(B, create_coordinate(3, 1), 4)
B = board_fill_position(B, create_coordinate(3, 2), 2)
B = board_fill_position(B, create_coordinate(4, 1), 4)
B = board_fill_position(B, create_coordinate(4, 3), 2)
B = board_reduce(B, 'W')
print_board(B)
B = create_board()
B = board_fill_position(B, create_coordinate(1, 1), 2)
B = board_fill_position(B, create_coordinate(1, 4), 4)
B = board_fill_position(B, create_coordinate(2, 2), 2)
B = board_fill_position(B, create_coordinate(2, 3), 4)
B = board_fill_position(B, create_coordinate(3, 1), 2)
B = board_fill_position(B, create_coordinate(3, 3), 4)
B = board_fill_position(B, create_coordinate(4, 3), 4)
B = board_fill_position(B, create_coordinate(4, 4), 2)
B = board_reduce(B, 'E')
print_board(B)
B = create_board()
B = board_fill_position(B, create_coordinate(1, 2), 2)
B = board_fill_position(B, create_coordinate(1, 4), 2)
B = board_fill_position(B, create_coordinate(2, 1), 2)
B = board_fill_position(B, create_coordinate(3, 1), 4)
B = board_fill_position(B, create_coordinate(3, 2), 4)
B = board_fill_position(B, create_coordinate(3, 3), 4)
B = board_fill_position(B, create_coordinate(4, 3), 2)
B = board_fill_position(B, create_coordinate(4, 4), 4)
B = board_reduce(B, 'N')
print_board(B)
B = create_board()
B = board_fill_position(B, create_coordinate(1, 1), 4)
B = board_fill_position(B, create_coordinate(1, 2), 4)
B = board_fill_position(B, create_coordinate(1, 4), 2)
B = board_fill_position(B, create_coordinate(2, 2), 2)
B = board_fill_position(B, create_coordinate(2, 3), 2)
B = board_fill_position(B, create_coordinate(3, 1), 2)
B = board_fill_position(B, create_coordinate(3, 3), 4)
B = board_fill_position(B, create_coordinate(3, 4), 8)
B = board_fill_position(B, create_coordinate(4, 3), 8)
B = board_fill_position(B, create_coordinate(4, 4), 8)
B = board_reduce(B, 'S')
print_board(B)
B = create_board()
B = board_fill_position(B, create_coordinate(1, 1), 8)
B = board_fill_position(B, create_coordinate(1, 2), 2)
B = board_fill_position(B, create_coordinate(1, 3), 4)
B = board_fill_position(B, create_coordinate(2, 1), 8)
B = board_fill_position(B, create_coordinate(2, 2), 2)
B = board_fill_position(B, create_coordinate(2, 4), 4)
B = board_fill_position(B, create_coordinate(3, 1), 8)
B = board_fill_position(B, create_coordinate(3, 3), 4)
B = board_fill_position(B, create_coordinate(3, 4), 2)
B = board_fill_position(B, create_coordinate(4, 1), 8)
B = board_fill_position(B, create_coordinate(4, 3), 2)
B = board_fill_position(B, create_coordinate(4, 4), 4)
B = board_reduce(B, 'W')
print_board(B)
B = create_board()
B = board_fill_position(B, create_coordinate(1, 1), 16)
B = board_fill_position(B, create_coordinate(1, 2), 8)
B = board_fill_position(B, create_coordinate(1, 3), 4)
B = board_fill_position(B, create_coordinate(1, 4), 2)
B = board_reduce(B, 'N')
B = board_reduce(B, 'S')
B = board_reduce(B, 'E')
B = board_reduce(B, 'W')
print_board(B)