## ========================================================================== ##
## -------------------------------------------------------------------------- ##
##                                 TEST 13                                    ##
## -------------------------------------------------------------------------- ##
## ========================================================================== ##

# -- Best: game
B = create_board()
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(3, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(3, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(3, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(3, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(3, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
N
B = board_reduce(B, M)
C = create_coordinate(4, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(4, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(3, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(3, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(2, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
W
B = board_reduce(B, M)
C = create_coordinate(1, 4)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 3)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 2)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(2, 4)
B = board_fill_position(B, C, 4)
print_board(B)
M = request_move()
E
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
M = request_move()
S
B = board_reduce(B, M)
C = create_coordinate(1, 1)
B = board_fill_position(B, C, 2)
print_board(B)
board_finished(B)
