## ========================================================================== ##
## -------------------------------------------------------------------------- ##
##                                 TESTE 13                                   ##
## -------------------------------------------------------------------------- ##
## ========================================================================== ##

# -- Teste: jogo
T = cria_tabuleiro()
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
N
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(4, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(3, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
W
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 4)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 3)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 2)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(2, 4)
T = tabuleiro_preenche_posicao(T, C, 4)
escreve_tabuleiro(T)
J = pede_jogada()
E
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
J = pede_jogada()
S
T = tabuleiro_reduz(T, J)
C = cria_coordenada(1, 1)
T = tabuleiro_preenche_posicao(T, C, 2)
escreve_tabuleiro(T)
tabuleiro_terminado(T)
